# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ytsongdw 0.1.3 ruby lib

Gem::Specification.new do |s|
  s.name = "ytsongdw"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["teonimesic", "ggouzi"]
  s.date = "2017-01-05"
  s.description = "Supports youtube urls, playlists and fulltext search"
  s.email = "stefano@heavenstudio.com.br"
  s.executables = ["ytsongdw"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".codeclimate.yml",
    ".rspec",
    ".rubocop.yml",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/ytsongdw",
    "lib/counter.rb",
    "lib/downloader.rb",
    "lib/file_settings.rb",
    "lib/playlist_downloader.rb",
    "lib/simple_logger.rb",
    "lib/song_downloader.rb",
    "lib/youtube_song_downloader.rb",
    "lib/ytsongdw.rb",
    "songs.txt",
    "spec/spec_helper.rb",
    "spec/test.txt",
    "spec/youtube_song_downloader_spec.rb",
    "ytsongdw.gemspec"
  ]
  s.homepage = "http://github.com/heavenstudio/ytsongdw"
  s.licenses = ["GPL-2.0"]
  s.required_ruby_version = Gem::Requirement.new(">= 2.0")
  s.rubygems_version = "2.5.1"
  s.summary = "Gem to download songs from youtube videos"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<memoist>, ["~> 0"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.6"])
      s.add_runtime_dependency(%q<scrapifier>, ["~> 0"])
      s.add_runtime_dependency(%q<youtube-dl.rb>, ["~> 0"])
      s.add_development_dependency(%q<codeclimate-test-reporter>, ["~> 1.0"])
      s.add_development_dependency(%q<pry>, ["~> 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<rspec>, ["~> 3.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0"])
      s.add_development_dependency(%q<juwelier>, ["~> 2.1"])
    else
      s.add_dependency(%q<memoist>, ["~> 0"])
      s.add_dependency(%q<nokogiri>, ["~> 1.6"])
      s.add_dependency(%q<scrapifier>, ["~> 0"])
      s.add_dependency(%q<youtube-dl.rb>, ["~> 0"])
      s.add_dependency(%q<codeclimate-test-reporter>, ["~> 1.0"])
      s.add_dependency(%q<pry>, ["~> 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<rspec>, ["~> 3.0"])
      s.add_dependency(%q<simplecov>, ["~> 0"])
      s.add_dependency(%q<juwelier>, ["~> 2.1"])
    end
  else
    s.add_dependency(%q<memoist>, ["~> 0"])
    s.add_dependency(%q<nokogiri>, ["~> 1.6"])
    s.add_dependency(%q<scrapifier>, ["~> 0"])
    s.add_dependency(%q<youtube-dl.rb>, ["~> 0"])
    s.add_dependency(%q<codeclimate-test-reporter>, ["~> 1.0"])
    s.add_dependency(%q<pry>, ["~> 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<rspec>, ["~> 3.0"])
    s.add_dependency(%q<simplecov>, ["~> 0"])
    s.add_dependency(%q<juwelier>, ["~> 2.1"])
  end
end

